#!/bin/bash

if [ $# -lt 1 ] ; then
    echo "usage: $0 <build|install|boot|test|patchcheck>..." >&2
    exit 1
fi

CONFFILE=ktest.conf
SUBCOMMAND=$1
case $SUBCOMMAND in
    build|install|boot)
    ;;
    test)
	if [ $# -lt 2 ] ; then
	    echo "usage: $0 test <test path>" >&2
	    exit 1
	fi

	TEST=$2
	if [ ! -f ${TEST} -o ! -x ${TEST} ] ; then
	    echo "${TEST} should be executable test program" >&2
	    exit 1
	fi
	TEST=$(realpath ${TEST})
    ;;
    patchcheck)
	if [ $# -lt 4 ] ; then
	    echo "usage: $0 patchcheck <start> <end> [build|install|boot|test] [test path]" >&2
	    echo "	<start>: the first patch of the test target patchset" >&2
	    echo "	<end>: the last patch of the test target patchset" >&2
	    exit 1
	fi
	PATCHCHECK_START=$2
	PATCHCHECK_END=$3
	PATCHCHECK_TYPE=$4
	case $PATCHCHECK_TYPE in
	    build|install|boot)
	    ;;
	    test)
		if [ $# -lt 5 ] ; then
		    echo "usage: $0 patchcheck <start> <end> test <test path>" >&2
		    exit 1
		fi
		TEST=$2
		if [ ! -f ${TEST} -o ! -x ${TEST} ] ; then
		    echo "${TEST} should be executable test program" >&2
		    exit 1
		fi
		TEST=$(realpath ${TEST})
		;;
	    *)
		echo "usage: $0 patchcheck <start> <end> [build|install|boot|test] [test path]" >&2
		echo "	<start>: the first patch of the test target patchset" >&2
		echo "	<end>: the last patch of the test target patchset" >&2
		exit 1		
		;;
	esac
	;;
    *)
	echo "subcommand shoulld be <build|install|boot|test|patchcheck>: ${SUBCOMMAND}" >&2
	exit 1
    ;;
esac

trap "_cleanup ; exit 0" 0 1 2 3 15

function _cleanup {
    restore_ktest_conf
}

function modify_ktest_conf {
    sed -i -e '/^TEST_START/,$s/^/# /' $CONFFILE
    sed -i -e '$aTEST_START' $CONFFILE

    sed -i -e "\$aTEST_TYPE = ${SUBCOMMAND}" $CONFFILE
    case $SUBCOMMAND in
	test)
	    sed -i -e "\$aTEST = ${TEST}" $CONFFILE
	    ;;
	patchcheck)
	    sed -i -e "\$aPATCHCHECK_START = ${PATCHCHECK_START}" $CONFFILE
	    sed -i -e "\$aPATCHCHECK_END = ${PATCHCHECK_END}" $CONFFILE
	    sed -i -e "\$aPATCHCHECK_TYPE = ${PATCHCHECK_TYPE}" $CONFFILE
	    if [ $PATCHCHECK_TYPE = test ] ; then
		sed -i -e "\$aTEST = ${TEST}" $CONFFILE
	    fi
	    ;;
    esac
}

function restore_ktest_conf {
    sed -i -e '/^TEST_START/,$d' $CONFFILE
    sed -i -e '/^# TEST_START/,$s/^# //' $CONFFILE
}

cd ktest
modify_ktest_conf
./ktest.pl
