#!/bin/bash

KERNELDIR=$(realpath ../../output)

build_driver() {
    pushd walb-driver/module
    make KERNELDIR=${KERNELDIR} -j8
    popd
}
,
build_tools() {
    pushd walb-tools
    make -j8
    popd
}

build_driver
build_tools
